### ISSUE TITLE
[Idea] sd as a plugin :)

### ISSUE THREAD

**Issue by gerardbosch** [ianthehenry/dotfiles#1]
Hi there!

I landed this post https://ianthehenry.com/posts/sd-my-script-directory/ and I found your `sd` interesting.

Have you considered moving it to a dedicated repository so other people can include it as a git submodule to their own dotfiles or ideally could be installed with a ZSH plugin manager like Antigen or similar? Something to keep up with potential future updates.

Cheers!

**Comment by ianthehenry** [comment]
Hmm. That's a good idea.

So there's not really anything shell-specific about `sd`, so I don't think it makes sense to distribute it as a shell plugin -- it's basically just a simple executable that happens to be implemented in shell. I think it would make more sense to distribute `sd` and the associated shell completion script through a standard package manager, but I don't think it's quite "good enough" for that yet.

It does make sense to split it into its own repo, though. I didn't realize how many people were starring my dotfiles, presumably just because of this!

https://github.com/ianthehenry/sd

**Comment by gerardbosch** [comment]
That's fantastic :clap: :clap: :clap:, and thanks for attending my request :)

I've added it as a submodule to my own dotfiles :D

One question, when you say «_So there's not really anything shell-specific about sd_» do you mean "nothing specific to ZSH"? Is that the reason why it shouldn't be distributed as a shell plugin? I found plugin managers a very convenient and easy way to install stuff, but I'm not sure how many changes should be done to allow installation and update handling just by adding something like (or equiv.)
```
antigen bundle ianthehenry/sd
```
into my `.zshrc`.

That's easier than cloning as subrepo, making symlinks, adding completions to `fpath` and managing updates manually for the submodule.

Do you think that would be possible? I'm just thinking about possibilities.
Thanks! :smiley:

**Comment by ianthehenry** [comment]
Yeah, what I mean is that it's just a regular program that happens to come with shell completion. It doesn't really integrate with the shell in any way beyond that, so it doesn't seem like it belongs in antigen to me -- the same way you don't install git via antigen, even though git also ships with shell completion scripts.

But that said I have never used antigen, so I might be way off the mark there. I assume it's mostly things like syntax highlighting and `PS1` niceties and doesn't contain "regular" utilities like `rg` or `fd` or `sd`.

I do realize that the current "installation instructions" are an abomination, since they require the delicate dance of initializing `~/sd` with the correct helpers. The right fix for this, I think, is to write `sd` as a single program that bundles all of those commands into one executable, so that there are no such helper scripts necessary, and then the installation is just `brew install sd` or `apt-get install sd` or whatever. That would take care of putting the completion script into the standard location.

**Comment by gerardbosch** [comment]
> But that said I have never used antigen, so I might be way off the mark there. I assume it's mostly things like syntax highlighting and PS1 niceties and doesn't contain "regular" utilities like rg or fd or sd.

I'm not very expert in shell plugins, but just to mention that it seems there are plugins that go beyond modifying the shell appearance and that provide commands in form of shell functions. One example is `k` command: https://github.com/supercrabtree/k

The good part of that is how easy it is to both install and update plugins straight from GitHub.
What I'm not sure is if the "plugin" needs to be something purely ZSH specific, or there can be plugins that work with any shell (or at least in both bash and zsh).

That's why I thought that maybe `sd` could be installed as a shell plugin, just to simplify its management from the user side. But I don't know if the way it is implemented (`sd` as an executable) could fit that approach or it's impossible.

**Comment by ianthehenry** [comment]
Oh, that's interesting. Okay, yeah, that does look similar in spirit to `sd`. So I think it would be possible (and not actually much work at all) to reimplement `sd` as single shell script (basically inlining all of the `sdefaults/` commands as functions), and to bundle it possible to distribute it in antigen. I'll take a look at doing that some time this weekend.

**Comment by gerardbosch** [comment]
Cool man, you rock! There's plenty of plugin managers besides Antigen, there's zplug, antibody and a lot more. I think they all work in a similar way by adding a line in your `.zshrc` and the plugin clones and sources the function/s.

I think one particularity of Antigen is that requires a `sd.plugin.zsh` file, while other plugin managers seem not to require this. I've seen people use a symlink for `sd.plugin.zsh` for example to point the actual file where `sd` is defined.

Some plugins merely provide completions such as https://github.com/spwhitt/nix-zsh-completions

If I can help with anything, let me know :)
